DROP INDEX ASP.USU_I1;

CREATE UNIQUE INDEX ASP.USU_I1 ON ASP.USUARIOS
(ID_EMAIL, ID_LISTA)
LOGGING
TABLESPACE ASPIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;